# Generated by Django 3.2.3 on 2021-05-24 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_email_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='email',
        ),
    ]
